# ~/.config/starship.toml

add_newline = false
command_timeout = 1000
format = """(
$env_var\
$mise\
$python\
$rust\
$kubernetes\
$directory\
$git_branch\
$git_status\
)$line_break$character"""

# Drop default prompt characters
[character]
success_symbol = ''
error_symbol = ''

# ---

[os]
format = '[$symbol](bold white) '
disabled = false

[os.symbols]
Windows = ' '
Arch = '󰣇'
CachyOS = '󰣇'
Ubuntu = ''
Macos = '󰀵'
Pop = ''

# ---

# Shows current directory
[directory]
truncate_to_repo = false

# Shows current git branch
[git_branch]
symbol = ' '
format = 'via [$symbol$branch]($style)'
# truncation_length = 4
truncation_symbol = '…/'
style = 'bold green'

# Shows current git status
[git_status]
format = '([ \( $all_status$ahead_behind\)]($style) )'
style = 'bold green'
conflicted = '[ confliced=${count}](red) '
up_to_date = '[󰘽 up-to-date](green) '
untracked = '[󰋗 untracked=${count}](red) '
ahead = ' ahead=${count}'
diverged = ' ahead=${ahead_count}  behind=${behind_count}'
behind = ' behind=${count}'
stashed = '[ stashed=${count}](green) '
modified = '[󰛿 modified=${count}](yellow) '
staged = '[󰐗 staged=${count}](green) '
renamed = '[󱍸 renamed=${count}](yellow) '
deleted = '[󰍶 deleted=${count}](red) '

# Shows kubernetes context and namespace
[kubernetes]
format = '[󱃾 $context\($namespace\)](bold purple) '
disabled = false

[rust]
format = '[⚙️ $version](red bold) '
disabled = false

[python]
style = 'bold bright-green'
format = '[ ${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[env_var]

[env_var.MISE]
variable = "MISE_ENV"
format = '[[$symbol$env_value ](bold red)]($style)'
symbol = " "

[mise]
disabled = false
format = '[[$symbol](bold green)]($style)'
symbol = "󱁤 "
healthy_symbol = " "
unhealthy_symbol = " "
